spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yk?useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  data :
    solr:
      host: http://127.0.0.1:8983/solr

mybatis:
  mapper-locations: classpath:org/lanqiao/yk/dao/*.xml
  type-aliases-package: org.lanqiao.yk.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        yk:
          mapper : debug
